### PR TITLE
Upgraded Terraform SDK to v0.12.5 release

### PR DESCRIPTION
**Pull request by sergei-ivanov**

### CODE REVIEW

**Comment by appilon** [comment]
Hello @sergei-ivanov thank you for the contribution. Although it likely does not make any difference in terms of the libraries imported, could you bump the version to the latest version of terraform: v0.12.5? Followed by `go mod tidy` and `go mod vendor`. Thank you!

**Comment by sergei-ivanov** [comment]
@appilon OK, will do tonight. I actually did exactly that (upgrade to 0.12.5 dependency) yesterday after the rebasing, just to evaluate the volume of changes, but then decided to be conservative and stayed on 0.12.0.

**Comment by sergei-ivanov** [comment]
Done

**Comment by appilon** [comment]
okay tests are green thanks for the contribution!

**Pull request merged**
