### PR TITLE
Fix SOA detection logic to cover DNS servers returning a non-SOA record.

### PR DESCRIPTION
**Pull request by liebman**
If we receive an answer and it does not contain a SOA record then continue instead of breaking.

Sometimes DNS servers will return an answer that does not contain a SOA when they were asked for one.  For example the output of `dig -t SOA  www.terraform.io`:
```
; <<>> DiG 9.10.6 <<>> -t SOA www.terraform.io
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 64652
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4000
;; QUESTION SECTION:
;www.terraform.io.		IN	SOA

;; ANSWER SECTION:
www.terraform.io.	0	IN	CNAME	dualstack.s.shared.global.fastly.net.

;; Query time: 79 msec
;; SERVER: 172.24.23.5#53(172.24.23.5)
;; WHEN: Wed Mar 27 10:30:11 PDT 2019
;; MSG SIZE  rcvd: 95
```
This would cause import to fail on this record.

### CODE REVIEW

**Comment by liebman** [comment]
Tests are failing due to data_dns_txt_record_set_test.go issues, fixed in #78 and reverse lookup of 8.8.8.8 not returning "google-public-dns-a.google.com." as expected in the test env.

**Comment by bodgit** [comment]
Good catch, however the only time you won't get an SOA answer when asking for one, there will be a CNAME instead which should be tested for explicitly, so the fix should  be to just update the loop with the following:
```golang
			for _, ans := range r.Answer {
				switch t := ans.(type) {
				case *dns.SOA:
					zone = &t.Hdr.Name
                                case *dns.CNAME:
                                        continue Loop
				}
			}
```

**Comment by liebman** [comment]
@bodgit - your request has been incorporated.

**Comment by bodgit** [comment]
@liebman Sadly I don't have commit privileges, so I'm unable to merge this for you. We'll have to wait for someone from Hashicorp to do it.

**Pull request merged**
