### PR TITLE
Add NS records to DNS server. 

### PR DESCRIPTION
**Pull request by anuiq**
Have my changes committed into the master of my fork. 
The changes allow a user to add NS records to their DNS server.

### CODE REVIEW

**Comment by apparentlymart** [comment]
Hi @anuiq! Thanks for all this work.

This PR is targeting the our local `anuiq-ns-record` branch rather than the master branch, so I opened #8 with the same changes targeting master so that I can review and merge it.

**Comment by apparentlymart** [comment]
On second thought, I'm going to merge this into the `anuiq-ns-record` branch and then work from there. Sorry for the indecision and shuffle...

**Comment by apparentlymart** [comment]
Hi @anuiq,

When I tested this I found that there were some code formatting issues being caught by the `go fmt` tool.:

```
==> Checking that code complies with gofmt requirements...
gofmt needs running on the following files:
./dns/data_dns_ns_record_set.go
./dns/resource_dns_ns_record_set.go
./dns/provider.go
You can use the command: `make fmt` to reformat code.
GNUmakefile:30: recipe for target 'fmtcheck' failed
```

If you run `make fmt` before you commit this should be fixed automatically.

It looks like also the automated acceptance tests are still having issues with the `NXDOMAIN` issue:

```
=== RUN   TestAccDnsNSRecordSet_Basic
--- FAIL: TestAccDnsNSRecordSet_Basic (0.07s)
	testing.go:435: Step 0 error: Error applying: 1 error(s) occurred:
		
		* dns_ns_record_set.foo: 1 error(s) occurred:
		
		* dns_ns_record_set.foo: Error querying DNS record: 3
	testing.go:499: Error destroying resource! WARNING: Dangling resources
		may exist. The full state and error is shown below.
		
		Error: Error refreshing: 1 error(s) occurred:
		
		* dns_ns_record_set.foo: 1 error(s) occurred:
		
		* dns_ns_record_set.foo: dns_ns_record_set.foo: Error querying DNS record: 3
		
		State: <nil>
```

If you have Docker installed and you're on either Linux or Mac, you can run these tests using the script `dns/acceptance.sh` to see what I was seeing above. However, I had to make some fixes to that acceptance script which are now merged into master, so you'd need to rebase your change onto the latest changes to master before this will work.

Since I already did the rebase and the `make fmt` as part of my testing, I pushed [the updated commit](https://github.com/terraform-providers/terraform-provider-dns/commit/017ac5cbbbc55cb3e503cbc2b69697838201901c) to the same `anuiq-ns-record` branch as I did last time, which will maybe save you the trouble of repeating those steps yourself.

If you're now seeing this working on your local DNS server then it seems likely that the remaining issue is a bug in the test itself rather than in the code, but unfortunately we still need to get the test working since we use these acceptance tests to validate releases. :confounded: If you're not able to run the acceptance tests yourself but you have an idea of what might be causing the issue based on what you learned during your manual testing I can try to get the tests running on your behalf, but at this time I'm not sure what's going on.

Due to these issues I can't actually merge this to master, but yet I also can't undo the merging I already did into the `anuiq-ns-record` branch :disappointed: so unfortunately it will be necessary to open another PR to actually merge this. If you so, please be sure to set the base branch to `master`.

**Comment by anuiq** [comment]
Hey @apparentlymart 
I am not sure why the acceptance test is failing. I see the code working so seems like the problem is in the tests. The following were the problems I saw when I was getting these errors. 
1- The keyname in my terraform plan file did not end with a '.'
2- I was only adding 2 NS records but the dig was returning more. I think that might be because I added the SOA record and it picked up the rest from the route53 zone. 

I am not aware of what else could cause this issue. 

I tried to run the acceptance test but that did not work 

``` ./acceptance.sh
+ export DNS_DOMAIN_FORWARD=example.com.
+ DNS_DOMAIN_FORWARD=example.com.
+ export DNS_DOMAIN_REVERSE=1.168.192.in-addr.arpa.
+ DNS_DOMAIN_REVERSE=1.168.192.in-addr.arpa.
+ DOCKER_CONTAINER_NAME=tf_acc_dns
+ export DNS_UPDATE_SERVER=127.0.0.1
+ DNS_UPDATE_SERVER=127.0.0.1
+ export DNS_UPDATE_PORT=55354
+ DNS_UPDATE_PORT=55354
+ docker run -d -p 55354:53/udp -e BIND_DOMAIN_FORWARD=example.com. -e BIND_DOMAIN_REVERSE=1.168.192.in-addr.arpa. -e BIND_INSECURE=true --name tf_acc_dns drebes/bind
Unable to find image 'drebes/bind:latest' locally
latest: Pulling from drebes/bind
3d8673bd162a: Pull complete
2d8fdc137273: Pull complete
d99ba397069e: Pull complete
5eef67fd4bd0: Pull complete
155d9374dd6e: Pull complete
Digest: sha256:2757429335014f364e6439e33f2fb222cbb2ff849e895ee20ee89e6c674bd9a7
Status: Downloaded newer image for drebes/bind:latest
b7ffb9fae1125a757617506c0e4aad566a4e7cc16b2a786986211036c5b73f74
+ make testacc TEST=./dns
make: *** No rule to make target `testacc'.  Stop.
+ failed
+ cleanup_docker
+ docker stop tf_acc_dns
tf_acc_dns
+ docker rm tf_acc_dns
tf_acc_dns
+ exit 1 ```

I am not sure how to proceed after that. Are the steps for testing mentioned somewhere? I mean something of this sort: 
1- Run the acceptance script 
2- Run the plan and so on ... 

I am very thankful for your help.

**Comment by apparentlymart** [comment]
Thanks for this extra info @anuiq.

That error is interesting... it looks like it failed trying to run `make testacc`. My guess here would be that the `make` you have is not GNU make, and so it's not finding the `GNUmakefile` configuration. If you're on a Mac, perhaps installing `make` with homebrew will work but I'm afraid I'm not a Mac user myself so I'm not sure. :confounded: 

As an alternative you could work around this by temporarily editing the `dns/acceptance.sh` file to not depend on the makefile; just be sure not to commit this change!

There are two lines like the following in the script:

```
make testacc TEST=./dns || failed
```

I think it will work if you replace both of these lines with the following, which will just directly run the command that the makefile would've run:

```
TF_ACC=1 go test -v ./dns || failed
```

**Comment by anuiq** [comment]
Hey @apparentlymart 
So these are the steps I followed to replicate this issue that you are seeing 
I ran the docker container locally and not as a part of the test suite aka the acceptance script.
```
docker run -d -p 55354:53/udp \
        -e BIND_DOMAIN_FORWARD="example.com." \
        -e BIND_DOMAIN_REVERSE="1.168.192.in-addr.arpa." \
        -e BIND_KEY_NAME="example.com." \
        -e BIND_KEY_ALGORITHM="hmac-md5" \
        -e BIND_KEY_SECRET="c3VwZXJzZWNyZXQ=" \
        --name "localrun" drebes/bind
```
Now I was trying to use the provider executable using this terraform plan 

```
provider "dns" {
  update {
    server        = "127.0.0.1"
    port          = "55354"
    key_name      = "example.com."
    key_algorithm = "hmac-md5"
    key_secret    = "c3VwZXJzZWNyZXQ="
  }
}
resource "dns_ns_record_set" "foo1" {
  zone= "example.com."
  name = "foo1"
  nameservers = [
  "ns1.testdns.co.uk.",
  "ns2.testdns.co.uk.",
  ]
  ttl = 300
}
 resource "dns_a_record_set" "test2" {
  zone= "example.com."
  name = "test2"
  addresses = [
  "100.1.1.1",
  "100.2.2.2",
  "100.3.3.3",

  ]
  ttl = 300
}
```
Note: This approach works for A records and they are successfully added to the local DNS server running in the docker container. However, for NS records addition returns the NXDOMAIN error that you mentioned because its failing on this part :  resource_dns_ns_record_set.go 

```
func resourceDnsNSRecordSetRead(d *schema.ResourceData, meta interface{}) error {

	if meta != nil {

		rec_name := d.Get("name").(string)
		rec_zone := d.Get("zone").(string)

		if rec_zone != dns.Fqdn(rec_zone) {
			return fmt.Errorf("Error reading DNS record: \"zone\" should be an FQDN")
		}

               rec_fqdn := fmt.Sprintf("%s.%s", rec_name, rec_zone)

		c := meta.(*DNSClient).c
		log.Printf("************** c: ,%s", c)

		srv_addr := meta.(*DNSClient).srv_addr
		log.Printf("**************srv_addr :: %s ,%s", srv_addr)

		msg := new(dns.Msg)
		msg.SetQuestion(rec_fqdn, dns.TypeNS)
		log.Printf("**************msg :: %s", msg)

		**r, _, err := c.Exchange(msg, srv_addr)
		log.Printf("************** r :: %s", r)**

```
r contains an error code. It has NXDOMAIN for the status value which is causing r.Answer to not have values in it causing the apply to fail. 
I am not sure why c.Exchange does not work because that would be the dns library part and I am not very well versed with dynamic dns. 
These are the logs. They have logging that I added where it prints out all of the variables 

```
2017-08-24T16:00:46.377-0700 [DEBUG] plugin.terraform-provider-dns: 2017/08/24 16:00:46 ************** r :: ;; opcode: QUERY, status: NXDOMAIN, id: 11922
2017-08-24T16:00:46.377-0700 [DEBUG] plugin.terraform-provider-dns: ;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
2017-08-24T16:00:46.377-0700 [DEBUG] plugin.terraform-provider-dns:
2017-08-24T16:00:46.377-0700 [DEBUG] plugin.terraform-provider-dns: ;; QUESTION SECTION:
2017-08-24T16:00:46.377-0700 [DEBUG] plugin.terraform-provider-dns: ;foo1.example.com.	IN	 NS
2017-08-24T16:00:46.377-0700 [DEBUG] plugin.terraform-provider-dns: 2017/08/24 16:00:46 **************nameservers :: &{0x165ad50 map[] {{0 0} 0}}
2017-08-24T16:00:46.377-0700 [DEBUG] plugin.terraform-provider-dns: 2017/08/24 16:00:46 **************r answer :: []
2017/08/24 16:00:46 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* dns_ns_record_set.foo1: DNS record differs
2017/08/24 16:00:46 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* dns_ns_record_set.foo1: DNS record differs
2017/08/24 16:00:46 [DEBUG] plugin: waiting for all plugin processes to complete...
```
I think I am out of ideas as to why this might be failing. Please let me know if I am missing something.

**Pull request merged**
